"""
ADAVID v4.0 — Pharmaceutical Audit Engine
Licensed under AGPL v3 (see LICENSE). Copyright (c) 2026 ADAVID Contributors.

ADAVID v4.0 — Improvement #1: Real Live Data Clients
Gap in v3: faers_integration.py returns mock data. ClinicalTrials.gov was scaffolded but never wired.
This module: real HTTP clients with retry, caching, rate limiting, ETag support.
"""

import hashlib
import json
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from urllib.parse import urlencode

try:
    import requests
        HAS_REQUESTS = True
        except ImportError:
            HAS_REQUESTS = False


            @dataclass
            class RateLimiter:
                """Token-bucket rate limiter — protects against API bans."""
                    max_per_minute: int = 60
                        _calls: List[float] = field(default_factory=list)

                            def acquire(self) -> None:
                                    now = time.time()
                                            self._calls = [t for t in self._calls if now - t < 60]
                                                    if len(self._calls) >= self.max_per_minute:
                                                                sleep_for = 60 - (now - self._calls[0]) + 0.1
                                                                            time.sleep(max(0, sleep_for))
                                                                                    self._calls.append(time.time())


                                                                                    class LiveDataClient:
                                                                                        """
                                                                                            Base class for real API clients. Handles:
                                                                                                - Exponential backoff retry (network errors, 5xx, 429)
                                                                                                    - Response caching with TTL
                                                                                                        - Rate limiting
                                                                                                            - ETag / If-None-Match support
                                                                                                                """

                                                                                                                    def __init__(self, base_url: str, rate_limit_per_min: int = 60,
                                                                                                                                     cache_ttl_seconds: int = 3600, max_retries: int = 3):
                                                                                                                                             self.base_url = base_url.rstrip("/")
                                                                                                                                                     self.rate_limiter = RateLimiter(max_per_minute=rate_limit_per_min)
                                                                                                                                                             self.cache_ttl = cache_ttl_seconds
                                                                                                                                                                     self.max_retries = max_retries
                                                                                                                                                                             self._cache: Dict[str, Dict] = {}
                                                                                                                                                                                     self._etags: Dict[str, str] = {}

                                                                                                                                                                                         def _cache_key(self, path: str, params: Optional[Dict]) -> str:
                                                                                                                                                                                                 raw = f"{path}?{urlencode(sorted((params or {}).items()))}"
                                                                                                                                                                                                         return hashlib.sha256(raw.encode()).hexdigest()

                                                                                                                                                                                                             def _cache_get(self, key: str) -> Optional[Any]:
                                                                                                                                                                                                                     entry = self._cache.get(key)
                                                                                                                                                                                                                             if not entry:
                                                                                                                                                                                                                                         return None
                                                                                                                                                                                                                                                 if time.time() - entry["stored_at"] > self.cache_ttl:
                                                                                                                                                                                                                                                             del self._cache[key]
                                                                                                                                                                                                                                                                         return None
                                                                                                                                                                                                                                                                                 return entry["data"]

                                                                                                                                                                                                                                                                                     def _cache_set(self, key: str, data: Any) -> None:
                                                                                                                                                                                                                                                                                             self._cache[key] = {"data": data, "stored_at": time.time()}

                                                                                                                                                                                                                                                                                                 def get(self, path: str, params: Optional[Dict] = None,
                                                                                                                                                                                                                                                                                                             use_cache: bool = True) -> Dict:
                                                                                                                                                                                                                                                                                                                     """GET with retry + cache + rate limit."""
                                                                                                                                                                                                                                                                                                                             cache_key = self._cache_key(path, params)
                                                                                                                                                                                                                                                                                                                                     if use_cache:
                                                                                                                                                                                                                                                                                                                                                 cached = self._cache_get(cache_key)
                                                                                                                                                                                                                                                                                                                                                             if cached is not None:
                                                                                                                                                                                                                                                                                                                                                                             return {"_cached": True, "data": cached}

                                                                                                                                                                                                                                                                                                                                                                                     if not HAS_REQUESTS:
                                                                                                                                                                                                                                                                                                                                                                                                 return {"_error": "requests library not installed", "_offline": True}

                                                                                                                                                                                                                                                                                                                                                                                                         url = f"{self.base_url}/{path.lstrip('/')}"
                                                                                                                                                                                                                                                                                                                                                                                                                 headers = {"Accept": "application/json", "User-Agent": "ADAVID/4.0"}
                                                                                                                                                                                                                                                                                                                                                                                                                         if cache_key in self._etags:
                                                                                                                                                                                                                                                                                                                                                                                                                                     headers["If-None-Match"] = self._etags[cache_key]

                                                                                                                                                                                                                                                                                                                                                                                                                                             last_err = None
                                                                                                                                                                                                                                                                                                                                                                                                                                                     for attempt in range(self.max_retries):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 self.rate_limiter.acquire()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             r = requests.get(url, params=params, headers=headers, timeout=30)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if r.status_code == 304:  # Not Modified
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return {"_cached": True, "_not_modified": True,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             "data": self._cache_get(cache_key)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if r.status_code == 429:  # Rate limited
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 time.sleep(2 ** attempt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     if r.status_code >= 500:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         time.sleep(2 ** attempt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             continue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             r.raise_for_status()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             data = r.json()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if "ETag" in r.headers:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 self._etags[cache_key] = r.headers["ETag"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 self._cache_set(cache_key, data)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return {"_cached": False, "data": data}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             last_err = e
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             time.sleep(2 ** attempt)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     return {"_error": str(last_err), "_failed_after_retries": self.max_retries}


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     class ClinicalTrialsClient(LiveDataClient):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         """Real client for ClinicalTrials.gov API v2."""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             def __init__(self):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     super().__init__("https://clinicaltrials.gov/api/v2",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rate_limit_per_min=50, cache_ttl_seconds=7200)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  def search_studies(self, query: str, page_size: int = 20) -> Dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return self.get("studies", {"query.term": query, "pageSize": page_size,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "format": "json"})

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   def get_study(self, nct_id: str) -> Dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return self.get(f"studies/{nct_id}", {"format": "json"})


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           class FAERSLiveClient(LiveDataClient):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               """Real FDA FAERS client — replaces v3's mock."""

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   def __init__(self, api_key: Optional[str] = None):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           super().__init__("https://api.fda.gov/drug/event.json",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rate_limit_per_min=240, cache_ttl_seconds=3600)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.api_key = api_key

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                def search(self, drug_name: str, limit: int = 100) -> Dict:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        params = {"search": f"patient.drug.medicinalproduct:{drug_name}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "limit": limit}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if self.api_key:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              params["api_key"] = self.api_key
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return self.get("", params)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      